Added --stdout option, updated some deps
sindresorhus/file-icon-cli pull request #2
Opened 2018-03-11 11:19 UTC by iamnapo

Fixed #1 

I happened to use it, saw the issue and thought to add it 😛

2018-03-20 18:06 UTC, iamnapo commented
@sindresorhus what do you think?

2018-03-21 19:23 UTC, kevva commented
Instead of an option, couldn't we just check if `process.stdout.isTTY` is `false`?

2018-03-21 20:10 UTC, iamnapo commented
I didn't think of that, should I change it?

2018-03-21 20:20 UTC, kevva commented
Yup. If you can avoid introducing a new option, it's good :).

2018-03-21 22:21 UTC, iamnapo commented
I'm not sure how to use execa to test for the default option(return icons location) now.

2018-03-22 11:31 UTC, kevva requested changes

2018-03-22 11:31 UTC, kevva commented on readme.md
> +```bash
Remove this and the one before.

2018-03-22 11:31 UTC, kevva commented on readme.md
> +    $ file-icon Safari > icon.png
Move this to the bottom instead. Looks better with it not having any logged output.

2018-03-22 11:31 UTC, kevva commented on test.js
> +	t.true((await execa.stdout('./cli.js', ['Safari'])).startsWith(Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])));
I would use `file-icon` in here and get the icon buffer first and then compare it to the one outputted by the CLI.

2018-03-22 11:32 UTC, kevva commented
> I'm not sure how to use execa to test for the default option (return icon's location) now.

You could just set `process.stdout.isTTY` to `true` manually in the test and then reset it to whatever it was before.

2018-03-22 12:44 UTC, iamnapo commented
> You could just set `process.stdout.isTTY` to `true` manually in the test and then reset it to whatever it was before.

Inside the test it's already true, the problem is inside the child process that is created.

2018-03-22 12:49 UTC, kevva commented
Oh right, you could pass `stdio: 'inherit'` to `execa` and it should work.

2018-03-22 13:01 UTC, iamnapo commented
It does, but I can't capture the output 😕

2018-03-22 13:13 UTC, iamnapo commented
The `process.stdout.isTTY` is `undefined`. No? 😕

2018-03-24 20:56 UTC, iamnapo commented
I think we can skip this test after all.

2018-03-29 23:35 UTC, iamnapo commented
Friendly ping @kevva :relaxed:

2018-04-14 18:48 UTC, iamnapo commented
Friendly ping @kevva @sindresorhus :relaxed: (I think we can skip this test, after all)

2018-05-06 07:56 UTC, sindresorhus commented
The trick to make it work in `execa` is to not check `process.stdout.isTTY`, but rather to just assume piping when there are no arguments.

2018-05-06 07:58 UTC, sindresorhus requested changes

2018-05-06 07:58 UTC, sindresorhus commented on test.js
> -	t.true((await execa.stdout('./cli.js', ['Safari'])).endsWith('icon.png'));
Please preserve the existing test.

2018-05-06 07:58 UTC, sindresorhus commented on readme.md
> -
Don't do unrelated changes.

2018-05-06 07:58 UTC, sindresorhus commented on package.json
> +		"tempy": "^0.2.1"
Don't do unrelated changes.

2018-05-06 12:59 UTC, iamnapo commented
but even when piping, there will be arguments. No?

2018-05-06 14:39 UTC, sindresorhus commented
Ah yeah, that's true... I guess we can just pass down an environment variable in the test and check for it in the code. Just for testing. Like `__FILE_ICON_SHOULD_PIPE__`. It's ugly, but at least then we can test it.

2018-05-06 18:12 UTC, iamnapo commented
Hmm. The problem is that `execa` runs the command in a child process, and in that child process `process.stdout.isTTY` is always `false`. So maybe you meant an env variable `__FILE_ICON_SHOULD_NOT_PIPE__`? If so, I think that an option like `--no-pipe` would be better: we can test it and lets someone pipe the location of the image as well.

2018-05-08 12:55 UTC, sindresorhus commented
> So maybe you meant an env variable __FILE_ICON_SHOULD_NOT_PIPE__? 

Yes, I said environment variable.

> If so, I think that an option like --no-pipe would be better: we can test it and lets someone pipe the location of the image as well.

I don't want to expose it as a flag to users. We only need this workaround for testing.

2018-05-27 09:33 UTC, sindresorhus commented
Thanks for your patience, @iamnapo. It looks good now :)

2018-05-27 09:33 UTC, merged